name: PyPI Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Choose build type: nightly or release'
        required: true
        default: 'nightly'
        options:
          - nightly
          - release

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirementst.txt
        pip install setuptools wheel twine
    - name: Build package
      run: |
        if [ "${{ github.event.inputs['build-type'] }}" = "nightly" ]; then
          export TORCHAO_NIGHTLY=1
        fi
        pip install .
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository_url: https://upload.pypi.org/legacy/
        packages_dir: dist/
