name: PyTorch CUDA Nightly Smoke Test

on:
  # run every day at 1:15pm
  schedule:
    - cron: "15 13 * * *"

concurrency:
  group: regression_test-${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

env:
  HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: CUDA Nightly
            runs-on: linux.g5.12xlarge.nvidia.gpu
            torch-spec: '--pre torch --index-url https://download.pytorch.org/whl/nightly/cu121'
            gpu-arch-type: "cuda"
            gpu-arch-version: "12.1"


    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: ${{ matrix.runs-on }}
      gpu-arch-type: ${{ matrix.gpu-arch-type }}
      gpu-arch-version: ${{ matrix.gpu-arch-version }}
      script: |
        python -m pip install --upgrade pip
        pip install ${{ matrix.torch-spec }}
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        python setup.py install
        pytest test --verbose -s
