name: Run Regression Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        include:
          - name: CUDA 2.2.2
            runs-on: 4-core-ubuntu-gpu-t4
            torch-spec: 'torch==2.2.2'
          - name: CUDA 2.3 RC
            runs-on: 4-core-ubuntu-gpu-t4
            torch-spec: 'torch==2.3.0 --index-url https://download.pytorch.org/whl/test/cu121'
          - name: CUDA Nightly
            runs-on: 4-core-ubuntu-gpu-t4
            torch-spec: '--pre torch --index-url https://download.pytorch.org/whl/nightly/cu121'
          - name: CPU 2.2.2
            runs-on: 32-core-ubuntu
            torch-spec: 'torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu'
          - name: CPU 2.3 RC
            runs-on: 32-core-ubuntu
            torch-spec: 'torch==2.3.0 --index-url https://download.pytorch.org/whl/test/cpu'
          - name: Nightly CPU
            runs-on: 32-core-ubuntu
            torch-spec: '--pre torch --index-url https://download.pytorch.org/whl/nightly/cpu'
    runs-on: ${{ matrix.runs-on }}
    # continue-on-error: true

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        python -m pip install --upgrade pip
        python -m pip install ${{ matrix.torch-spec }}
        python -m pip install -r requirements.txt
        python -m pip install -r dev-requirements.txt

    - name: Install package
      run: |
        source env/bin/activate
        python -m pip install .

    - name: Run tests
      run: |
        source env/bin/activate
        pytest test --verbose -s
