name: Run Regression Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        include:
          - name: CUDA Nightly
            runs-on: 4-core-ubuntu-gpu-t4
            torch-spec: '--pre torch --index-url https://download.pytorch.org/whl/nightly/cu121'
            cuda: '12.1.0'
    runs-on: ${{ matrix.runs-on }}
    container:
      image: nvidia/cuda:12.1.0-devel-ubuntu20.04
      ports:
        - 80
      options: --gpus all --shm-size "8G"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install ${{ matrix.torch-spec }}
        pip install -r requirements.txt
        pip install -r dev-requirements.txt

    - name: Install package
      run: |
        pip install . -vvv

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest test test/test_ops.py
