name: Run Regression Tests

on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main

jobs:

 test:
   strategy:
     matrix:
       config:
         - {name: 'cuda-2-0-1',   runner: '4-core-ubuntu-gpu-t4', torch: 'torch==2.0.1'}
         - {name: 'cuda-2-1-2',   runner: '4-core-ubuntu-gpu-t4', torch: 'torch==2.1.2'}
         - {name: 'cuda-2-2-2',   runner: '4-core-ubuntu-gpu-t4', torch: 'torch==2.2.2'}
         - {name: 'cuda-nightly', runner: '4-core-ubuntu-gpu-t4', torch: '--pre torch --index-url https://download.pytorch.org/whl/nightly/cu121'}
         - {name: 'cpu',          runner: '32-core-ubuntu',       torch: 'torch --index-url https://download.pytorch.org/whl/cpu'}
         - {name: 'nightly-cpu',  runner: '32-core-ubuntu',       torch: '--pre torch --index-url https://download.pytorch.org/whl/nightly/cpu'}

   name: Test ${{ matrix.config.name }}
   runs-on: ${{ matrix.config.runner }}
   
   steps:
     - uses: actions/checkout@v2
       
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.9
         
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install ${{ matrix.config.torch }}
         pip install -r requirements.txt
         pip install -r dev-requirements.txt
         
     - name: Install package
       run: |
         pip install .
         
     - name: Run tests
       run: |
         pytest test --verbose -s -x
