name: Run Regression Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        include:
          - name: CPU 2.2.2
            runs-on: 32-core-ubuntu
            torch-spec: 'torch==2.2.2'
          - name: CPU 2.3 RC
            runs-on: 32-core-ubuntu
            torch-spec: 'torch==2.3.0'
          - name: Nightly CPU
            runs-on: 32-core-ubuntu
            torch-spec: 'torch'
          - name: CUDA 2.2.2
            runs-on: 4-core-ubuntu-gpu-t4
            torch-spec: 'torch==2.2.2'
          - name: CUDA 2.3 RC
            runs-on: 4-core-ubuntu-gpu-t4
            torch-spec: 'torch==2.3.0 --index-url https://download.pytorch.org/whl/test/cu121'
          - name: CUDA Nightly
            runs-on: 4-core-ubuntu-gpu-t4
            torch-spec: '--pre torch --index-url https://download.pytorch.org/whl/nightly/cu121'

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: '3.9'
        activate-environment: test-env
        use-only-tar-bz2: true # optional: use only bzip2 archives, smaller bandwidth usage

    - name: Install CUDA Toolkit
      run: conda install -c nvidia/label/cuda-12.1.0 cuda-toolkit

    - name: Install PyTorch and other dependencies
      run: |
        pip install ${{ matrix.torch-spec }}
        pip install -r requirements.txt
        pip install -r dev-requirements.txt

    - name: List dependencies
      run: |
        pip list
        which python

    - name: Install package
      run: |
        python -c "import torch; print(torch.__version__)"
        pip install .

    - name: Run tests
      run: |
        pytest test --verbose -s
