name: Run Regression Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        include:
          # - name: CUDA 2.2.2
          #   runs-on: 4-core-ubuntu-gpu-t4
          #   torch-spec: 'torch==2.2.2'
          # - name: CUDA 2.3 RC
          #   runs-on: 4-core-ubuntu-gpu-t4
          #   torch-spec: 'torch==2.3.0 --index-url https://download.pytorch.org/whl/test/cu121'
          - name: CUDA Nightly
            runs-on: 4-core-ubuntu-gpu-t4
            torch-spec: '--pre torch --index-url https://download.pytorch.org/whl/nightly/cu121'
          # - name: CPU 2.2.2
          #   runs-on: 32-core-ubuntu
          #   torch-spec: 'torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu'
          # - name: CPU 2.3 RC
          #   runs-on: 32-core-ubuntu
          #   torch-spec: 'torch==2.3.0 --index-url https://download.pytorch.org/whl/test/cpu'
          # - name: Nightly CPU
          #   runs-on: 32-core-ubuntu
          #   torch-spec: '--pre torch --index-url https://download.pytorch.org/whl/nightly/cpu'
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2

    # - name: Set up CUDA
    #   run: |
    #     wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
    #     sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
    #     sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
    #     sudo add-apt-repository "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
    #     sudo apt-get -y install cuda-12-1
    #   env:
    #     CUDA_VERSION: 12.1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ${{ matrix.torch-spec }}
        pip install -r requirements.txt
        pip install -r dev-requirements.txt

    - name: Install package
      run: |
        pip install . -vvv

    - name: Run tests
      run: |
        pytest test --verbose -s
