name: Run Regression Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: regression_test-${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

env:
  HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: CUDA 2.2.2
            runs-on: linux.g5.12xlarge.nvidia.gpu
            torch-spec: 'torch==2.2.2'
            gpu-arch-type: "cuda"
            gpu-arch-version: "12.1"
          - name: CUDA 2.3 RC
            runs-on: linux.g5.12xlarge.nvidia.gpu
            torch-spec: 'torch==2.3.0 --index-url https://download.pytorch.org/whl/test/cu121'
            gpu-arch-type: "cuda"
            gpu-arch-version: "12.1"
          - name: CUDA Nightly
            runs-on: linux.g5.12xlarge.nvidia.gpu
            torch-spec: '--pre torch --index-url https://download.pytorch.org/whl/nightly/cu121'
            gpu-arch-type: "cuda"
            gpu-arch-version: "12.1"
          - name: CPU 2.2.2
            runs-on: linux.4xlarge
            torch-spec: 'torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu'
            gpu-arch-type: "cpu"
            gpu-arch-version: ""
          - name: CPU 2.3 RC
            runs-on: linux.4xlarge
            torch-spec: 'torch==2.3.0 --index-url https://download.pytorch.org/whl/test/cpu'
            gpu-arch-type: "cpu"
            gpu-arch-version: ""
          - name: Nightly CPU
            runs-on: linux.4xlarge
            torch-spec: '--pre torch --index-url https://download.pytorch.org/whl/nightly/cpu'
            gpu-arch-type: "cpu"
            gpu-arch-version: ""

    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: ${{ matrix.runs-on }}
      gpu-arch-type: ${{ matrix.gpu-arch-type }}
      gpu-arch-version: ${{ matrix.gpu-arch-version }}
      script: |
        python -m pip install --upgrade pip
        pip install ${{ matrix.torch-spec }}
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        echo "HAS_GPU=$(python -c 'import torch; print(torch.cuda.is_available())')" >> $GITHUB_ENV
        python -c "import torch; print(torch.cuda.get_device_capability())"
        pip install .
        pytest test --verbose -s
